### ISSUE TITLE
Serve HTML Files with Nginx

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/git-workshop#144]
We need to define an nginx container in a docker-compose.yml file

the contianer should expose port 80, and all html file should be mounted into the container

the yml file could look like
```yml
version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/usr/share/nginx/html:ro
```

then we could have an nginx.conf like
```
server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}

```
